version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.7
jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t wackdonalds_restaurant_simulator ./src
            docker tag wackdonalds_restaurant_simulator tebogoyungmercykay/wackdonalds_restaurant_simulator:v0
            docker login -u tebogoyungmercykay -p $DOCKER_PASSWORD
            docker push tebogoyungmercykay/wackdonalds_restaurant_simulator
workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
